In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
## Define the vocabulary size
voc_size=10000

In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1991, 408, 9018, 5108],
 [1991, 408, 9018, 5222],
 [1991, 4266, 9018, 3785],
 [2586, 7858, 7946, 1783, 5924],
 [2586, 7858, 7946, 1783, 4199],
 [218, 1991, 4289, 9018, 728],
 [7403, 8705, 1398, 1783]]

In [23]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1991  408 9018 5108]
 [   0    0    0    0 1991  408 9018 5222]
 [   0    0    0    0 1991 4266 9018 3785]
 [   0    0    0 2586 7858 7946 1783 5924]
 [   0    0    0 2586 7858 7946 1783 4199]
 [   0    0    0  218 1991 4289 9018  728]
 [   0    0    0    0 7403 8705 1398 1783]]


In [26]:
## feature representation
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 657ms/step


array([[[-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [ 0.00345224,  0.00103526,  0.00540266,  0.04939729,
         -0.01021949,  0.03456056,  0.03404081, -0.01606935,
         -0.00106051, -0.02293468],
        [ 0.0341339 ,  0.02347359,  0.01223316,  0.02726397,
         -0.02396709,  0.04629494, -0.04876325, -0.03545439,
         -0.03731891, -0.014241  ],
        [-0.01881307, -0.04586829,  0.0107228 , -0.0

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 1991,  408, 9018, 5108], dtype=int32)

In [33]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [-0.04300404,  0.00762162,  0.0039313 ,  0.02792133,
         -0.03609618, -0.0159422 , -0.0099988 ,  0.04807525,
         -0.01673723,  0.02228048],
        [ 0.00345224,  0.00103526,  0.00540266,  0.04939729,
         -0.01021949,  0.03456056,  0.03404081, -0.01606935,
         -0.00106051, -0.02293468],
        [ 0.0341339 ,  0.02347359,  0.01223316,  0.02726397,
         -0.02396709,  0.04629494, -0.04876325, -0.03545439,
         -0.03731891, -0.014241  ],
        [-0.01881307, -0.04586829,  0.0107228 , -0.0